#!/usr/bin/env npx tsx
/**
 * Embeds the ELIZA CLI bundle as a base64 string constant.
 * Run after esbuild creates the bundle.
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const bundlePath = path.join(__dirname, "..", "dist", "agents", "eliza", "cli.bundle.js")
const outputPath = path.join(__dirname, "..", "src", "agents", "eliza", "bundle-content.ts")

if (!fs.existsSync(bundlePath)) {
  console.error(`Bundle not found at ${bundlePath}. Run 'npm run build:eliza-bundle' first.`)
  process.exit(1)
}

const bundleBytes = fs.readFileSync(bundlePath)
const b64 = bundleBytes.toString("base64")

const output = `/**
 * ELIZA CLI bundle content - auto-generated, do not edit.
 * Generated by scripts/embed-eliza-bundle.ts
 */

// eslint-disable-next-line
export const ELIZA_BUNDLE_B64 = ${JSON.stringify(b64)}
`

fs.writeFileSync(outputPath, output)
console.log(`Embedded ELIZA bundle (${bundleBytes.length} bytes, ${b64.length} b64 chars) into ${outputPath}`)
